#!/usr/bin/env python3
"""
Build the thesis data appendix: a PDF inventory + a ZIP of the raw CSVs.

The appendix contains ONLY the variables actually used by the analysis notebooks:
- participant_features_*.csv files are excluded (no notebook loads them)
- leakage / old-target columns are dropped from movie_features_*.csv
- scene_movie_metadata_*.csv is trimmed to the META_KEEP set used by the notebooks

To re-run after editing the descriptions / lead text below:
    python ml_dataset/scripts/build_data_appendix.py
"""
import csv
import html as html_mod
import subprocess
import zipfile
from pathlib import Path

# ═══════════════════════════════════════════════════════════════════════════
# ▼▼▼ EDITABLE TEXT — change these strings and re-run the script ▼▼▼
# ═══════════════════════════════════════════════════════════════════════════

APPENDIX_TITLE = "Thesis Data Appendix"

LEAD_PARAGRAPH = """\
The following data files contain every variable actually consumed by the analysis
notebooks in this thesis. Raw data variables and those that weren't utilized during ML/DL training are excluded.
"""

# Per-file descriptions shown under each file's header.
FILE_DESCRIPTIONS = {
    "movie_features_v6.csv":
        "Movie-level features for the 10 real Emognition films. Each row aggregates "
        "physiological signals (heart rate, electrodermal activity, peripheral skin "
        "temperature, accelerometry) and scene-aligned summaries across the 43 "
        "participants who watched the corresponding clip. Used as the real-data half "
        "of the n = 50 corpus used for regression and classification models.",
    "movie_features_v6_synthetic.csv":
        "40 synthetic movies generated by Gaussian-copula augmentation from the joint "
        "distribution of the 10 real films. Concatenated with the real file above to "
        "form the n = 50 augmented corpus.",
    "scene_movie_metadata_v6.csv":
        "Scene properties and movie-level metadata for the 10 real films (targeted "
        "emotion, clip duration, audiovisual structure, genre, release year, country "
        "of origin, categorical budget bracket) plus the outcome variables "
        "extracted as regression targets.",
    "scene_movie_metadata_v6_synthetic.csv":
        "Matching metadata for the 40 synthetic films.",
    "movie_features_v7_synthetic.csv":
        "10,000 synthetic movies used to train the MLP. Trained on n = 10,010 "
        "(10 real + 10,000 synth); evaluated with 5-fold CV "
        "and synth→real transfer (10 real films held out).",
    "scene_movie_metadata_v7_synthetic.csv":
        "Metadata for the 10,000 synthetic films generated.",
}

# Footer note shown under the inventory table.
INVENTORY_NOTE = (
    "The full raw CSV files for all retained entries are bundled as "
    "<code>thesis_data_appendix.zip</code> alongside this PDF. "
    "Each per-file section below shows the first and last sample rows and the "
    "complete column list after the analysis trim has been applied."
)

# ═══════════════════════════════════════════════════════════════════════════
# ▲▲▲ END EDITABLE TEXT ▲▲▲
# ═══════════════════════════════════════════════════════════════════════════

PROJECT = Path("/Users/davidtoma/Library/CloudStorage/GoogleDrive-tomadavid001@gmail.com/My Drive/MSC THESIS")
V6_DIR = PROJECT / "ml_dataset" / "data" / "model_ready" / "movie_success_v6"
V7_DIR = PROJECT / "ml_dataset" / "data" / "model_ready" / "movie_success_v7"
OUT_DIR = PROJECT / "ml_dataset" / "notebooks_appendix_pdf"
CHROME = "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"

# Columns dropped from movie_features_* (leakage list — matches Notebook 01 Cell 4)
MOVIE_FEATURES_DROP = {
    "budget_usd", "revenue_usd", "roi_percent", "success_class",
    "imdb_rating", "wom_multiplier", "wom_multiplier_log",
}

# Columns retained from scene_movie_metadata_* (META_KEEP — matches Notebook 01 Cell 4)
METADATA_KEEP = [
    "movie_id",
    "targeted_emotion", "clip_duration_s",
    "cut_count", "brightness", "motion_intensity", "audio_loudness",
    "silence_ratio", "music_presence", "dialogue_density",
    "face_screen_time_ratio", "lead_screen_time_ratio",
    "release_year", "genre_primary", "genre_secondary",
    "country_of_origin", "budget_categorical",
    "imdb_rating", "wom_multiplier", "wom_multiplier_log",
]

FILES = [
    ("ML — Real movie features",            V6_DIR / "movie_features_v6.csv",            "movie_features"),
    ("ML — Synthetic movie features",       V6_DIR / "movie_features_v6_synthetic.csv",  "movie_features"),
    ("ML — Real scene/movie metadata",      V6_DIR / "scene_movie_metadata_v6.csv",      "metadata"),
    ("ML — Synthetic scene/movie metadata", V6_DIR / "scene_movie_metadata_v6_synthetic.csv", "metadata"),
    ("DL — Synthetic movie features",       V7_DIR / "movie_features_v7_synthetic.csv",  "movie_features"),
    ("DL — Synthetic scene/movie metadata", V7_DIR / "scene_movie_metadata_v7_synthetic.csv", "metadata"),
]


def fmt(v):
    if v == "" or v is None:
        return "—"
    try:
        f = float(v)
        if abs(f) < 1e-3 and f != 0:
            return f"{f:.3e}"
        if f == int(f) and "." not in str(v):
            return v
        return f"{f:.4g}"
    except (ValueError, TypeError):
        s = str(v)
        return s if len(s) <= 40 else s[:37] + "…"


def filtered_header_and_keep_idx(header, kind):
    if kind == "movie_features":
        keep = [i for i, h in enumerate(header) if h not in MOVIE_FEATURES_DROP]
    else:
        wanted = [c for c in METADATA_KEEP if c in header]
        keep = [header.index(c) for c in wanted]
    return [header[i] for i in keep], keep


def read_csv_filtered(path, kind):
    with path.open(encoding="utf-8", errors="replace") as fh:
        reader = csv.reader(fh)
        full_header = next(reader)
        new_header, keep_idx = filtered_header_and_keep_idx(full_header, kind)
        first_rows, last_rows = [], []
        n_rows = 0
        for row in reader:
            n_rows += 1
            filtered = [row[i] if i < len(row) else "" for i in keep_idx]
            if len(first_rows) < 5:
                first_rows.append(filtered)
            last_rows.append(filtered)
            if len(last_rows) > 5:
                last_rows.pop(0)
    return new_header, first_rows, last_rows, n_rows, len(full_header) - len(new_header)


def render_sample(header, rows, col_slice):
    if not rows:
        return "<p><em>(no rows)</em></p>"
    th = "".join(f"<th>{html_mod.escape(header[i])}</th>" for i in col_slice)
    body = []
    for row in rows:
        cells = "".join(f"<td>{html_mod.escape(fmt(row[i]) if i < len(row) else '')}</td>" for i in col_slice)
        body.append(f"<tr>{cells}</tr>")
    return f"<table class='sample'><thead><tr>{th}</tr></thead><tbody>{''.join(body)}</tbody></table>"


def render_colist(header):
    rows_html = []
    n = len(header)
    rows = (n + 2) // 3
    for r in range(rows):
        cells = []
        for c in range(3):
            idx = c * rows + r
            if idx < n:
                cells.append(f"<td class='idx'>{idx+1}</td><td class='col'>{html_mod.escape(header[idx])}</td>")
            else:
                cells.append("<td></td><td></td>")
        rows_html.append(f"<tr>{''.join(cells)}</tr>")
    return f"<table class='colist'><tbody>{''.join(rows_html)}</tbody></table>"


inventory_rows = []
sections = []
for title, path, kind in FILES:
    rel = path.relative_to(PROJECT)
    header, first_rows, last_rows, n_rows, dropped = read_csv_filtered(path, kind)
    n_cols = len(header)
    fname = path.name
    desc = FILE_DESCRIPTIONS.get(fname, "")
    inventory_rows.append((title, str(rel), n_rows, n_cols, dropped, desc))

    head_cols = list(range(min(8, n_cols)))
    tail_cols = list(range(max(0, n_cols - 6), n_cols))
    drop_msg = f" &nbsp;|&nbsp; <span class='dropped'>{dropped} columns dropped by analysis trim</span>" if dropped else ""

    sections.append(f"""
<section class="file-section">
  <div class="badge">DATA FILE</div>
  <h1>{html_mod.escape(title)}</h1>
  <div class="meta"><span class="path">{html_mod.escape(str(rel))}</span> &nbsp;|&nbsp;
       <span class="shape">{n_rows:,} rows × {n_cols} columns (after trim)</span>{drop_msg}</div>
  <p class="desc">{html_mod.escape(desc)}</p>

  <h2>First 5 rows — first {len(head_cols)} columns</h2>
  {render_sample(header, first_rows, head_cols)}

  <h2>Last 5 rows — last {len(tail_cols)} columns</h2>
  {render_sample(header, last_rows, tail_cols)}

  <h2>Complete column list ({n_cols} columns)</h2>
  {render_colist(header)}
</section>
""")

inv_rows_html = "".join(
    f"<tr><td>{html_mod.escape(t)}</td><td class='path'>{html_mod.escape(p)}</td>"
    f"<td class='num'>{r:,}</td><td class='num'>{c}</td></tr>"
    for t, p, r, c, _, _ in inventory_rows
)

inventory_html = f"""
<section class="inventory">
  <h1>{html_mod.escape(APPENDIX_TITLE)}</h1>
  <p class="lead">{LEAD_PARAGRAPH.replace(chr(10), '<br>')}</p>
  <table class="inv">
    <thead><tr><th>File</th><th>Path</th><th class='num'>Rows</th><th class='num'>Columns</th></tr></thead>
    <tbody>{inv_rows_html}</tbody>
  </table>
  <p class="note">{INVENTORY_NOTE}</p>
</section>
"""

html = f"""<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>{html_mod.escape(APPENDIX_TITLE)}</title>
<style>
  @page {{ size: A4; margin: 16mm 12mm; }}
  body {{ font-family: -apple-system, "Helvetica Neue", Arial, sans-serif; color: #111; font-size: 9.5pt; }}
  h1 {{ font-size: 16pt; border-bottom: 2px solid #222; padding-bottom: 4px; margin: 0; }}
  h2 {{ font-size: 11pt; margin: 16px 0 6px; color: #333; }}
  .badge {{ display: inline-block; background: #222; color: white; padding: 3px 10px;
           font-size: 8.5pt; letter-spacing: 2px; text-transform: uppercase; margin-bottom: 8px; }}
  .meta {{ font-size: 9pt; color: #444; margin: 6px 0 10px; }}
  .path, .shape, code {{ font-family: "SF Mono", Menlo, Consolas, monospace; }}
  .path {{ color: #666; }}
  .dropped {{ color: #b15a00; }}
  .desc {{ color: #333; margin: 4px 0 14px; font-style: italic; }}
  .lead {{ font-size: 10pt; line-height: 1.45; color: #222; margin: 14px 0; }}
  .note {{ font-size: 9pt; color: #444; margin-top: 18px; padding: 10px 12px; background: #f4f4f4; border-left: 3px solid #222; }}
  table {{ border-collapse: collapse; width: 100%; font-size: 8pt; }}
  table.inv {{ font-size: 9pt; }}
  th, td {{ border: 1px solid #bbb; padding: 4px 6px; text-align: left; vertical-align: top; }}
  th {{ background: #eee; font-weight: 600; }}
  td.num, th.num {{ text-align: right; font-variant-numeric: tabular-nums; }}
  table.sample {{ font-family: "SF Mono", Menlo, Consolas, monospace; font-size: 7.5pt; }}
  table.sample td {{ word-break: break-word; }}
  table.colist {{ font-size: 7.5pt; }}
  table.colist td.idx {{ width: 28px; text-align: right; color: #888; font-variant-numeric: tabular-nums; }}
  table.colist td.col {{ font-family: "SF Mono", Menlo, Consolas, monospace; }}
  .file-section {{ page-break-before: always; }}
  .inventory {{ page-break-after: always; }}
</style></head>
<body>
{inventory_html}
{''.join(sections)}
</body></html>
"""

html_path = Path("/tmp/data_appendix.html")
html_path.write_text(html, encoding="utf-8")

pdf_path = OUT_DIR / "thesis_data_appendix.pdf"
subprocess.run([CHROME, "--headless=new", "--disable-gpu", "--no-pdf-header-footer",
                f"--print-to-pdf={pdf_path}", f"file://{html_path}"],
               check=True, capture_output=True)
print(f"PDF written: {pdf_path}  ({pdf_path.stat().st_size:,} bytes)")

zip_path = OUT_DIR / "thesis_data_appendix.zip"
with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED, compresslevel=9) as zf:
    for _, path, _ in FILES:
        zf.write(path, arcname=path.relative_to(PROJECT).as_posix())
print(f"ZIP written: {zip_path}  ({zip_path.stat().st_size:,} bytes, 6 files)")
